export const users = [
  {
    id: 1,
    name: 'Harriet Davitti',
    email: 'hdavitti0@163.com',
    avatar: 'https://robohash.org/quamfugitpariatur.png?size=100x100&set=set1',
    isVerified: false,
    teams: ['Backend', 'Design', 'Frontend'],
    username: 'hdavitti0',
  },
  {
    id: 2,
    name: 'Demetre Chucks',
    email: 'dchucks1@va.gov',
    avatar: 'https://robohash.org/doloriurequi.png?size=100x100&set=set1',
    isVerified: false,
    teams: ['QA', 'Devops', 'Frontend'],
    username: 'dchucks1',
  },
  {
    id: 3,
    name: 'Tedd Langsbury',
    email: 'tlangsbury2@freewebs.com',
    avatar: 'https://robohash.org/eiusrepellatoptio.png?size=100x100&set=set1',
    isVerified: true,
    teams: ['Frontend', 'Backend', 'QA'],
    username: 'tlangsbury2',
  },
  {
    id: 4,
    name: 'Thia Kermath',
    email: 'tkermath3@cyberchimps.com',
    avatar: 'https://robohash.org/eaautemvoluptatem.png?size=100x100&set=set1',
    isVerified: false,
    teams: ['QA', 'Design', 'Backend'],
    username: 'tkermath3',
  },
  {
    id: 5,
    name: 'Alister Steffans',
    email: 'asteffans4@usgs.gov',
    avatar: 'https://robohash.org/nonrerumquae.png?size=100x100&set=set1',
    isVerified: true,
    teams: ['QA', 'Devops', 'Backend'],
    username: 'asteffans4',
  },
  {
    id: 6,
    name: 'Fernanda Heffernan',
    email: 'fheffernan5@sogou.com',
    avatar: 'https://robohash.org/quinecessitatibusdolorem.png?size=100x100&set=set1',
    isVerified: false,
    teams: ['Frontend', 'QA', 'Backend'],
    username: 'fheffernan5',
  },
  {
    id: 7,
    name: 'Annmaria Franceschino',
    email: 'afranceschino6@dailymail.co.uk',
    avatar: 'https://robohash.org/quodbeataeautem.png?size=100x100&set=set1',
    isVerified: false,
    teams: ['Backend', 'Frontend', 'Design'],
    username: 'afranceschino6',
  },
  {
    id: 8,
    name: 'Kitty Lezemore',
    email: 'klezemore7@biglobe.ne.jp',
    avatar: 'https://robohash.org/expeditapossimustempore.png?size=100x100&set=set1',
    isVerified: false,
    teams: ['Design', 'Devops', 'Backend'],
    username: 'klezemore7',
  },
  {
    id: 9,
    name: 'Hadrian Wixey',
    email: 'hwixey8@about.me',
    avatar: 'https://robohash.org/eaquamlaborum.png?size=100x100&set=set1',
    isVerified: true,
    teams: ['Backend', 'Devops', 'QA'],
    username: 'hwixey8',
  },
  {
    id: 10,
    name: 'Jeremie Salters',
    email: 'jsalters9@cnbc.com',
    avatar: 'https://robohash.org/nihilquoest.png?size=100x100&set=set1',
    isVerified: false,
    teams: ['QA', 'Devops', 'Backend'],
    username: 'jsalters9',
  },
];
