name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.2]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --no-tags --prune --depth=5 origin master
      - run: npm ci
      - run: npx nx affected --target=lint
      - run: npx nx affected --target=test
